### ISSUE TITLE
nodemon: not found

### ISSUE THREAD

**Issue by shahalom** [yTakkar/Single-Page-Social-Network#10]
After ran the command `npm start` I got the following error:
==================

shahalom@microsolutionsbd ~/www/react-projects/React-Mini-Social-Network $ npm start

> single-page-social-network@1.0.0 start /home/shahalom/www/react-projects/React-Mini-Social-Network
> nodemon app.js

sh: 1: nodemon: not found

npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! single-page-social-network@1.0.0 start: `nodemon app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the single-page-social-network@1.0.0 start script 'nodemon app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the single-page-social-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs single-page-social-network
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls single-page-social-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shahalom/www/react-projects/React-Mini-Social-Network/npm-debug.log

==================

FYI, here is the content of .env file:
==
PORT=YOUR_PORT
MYSQL_HOST="host"
MYSQL_USER="root"
MYSQL_PASSWORD="123456"
MYSQL_DATABASE="react_mini_social_network"
MAIL="example@gmail.com"
MAIL_PASSWORD="mypass"
SESSION_SECRET_LETTER="asecret"
==

Do you have any idea why i am having the error?

**Comment by yTakkar** [comment]
You should first install nodemon globally!!
