### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by adesoye0** [yTakkar/Single-Page-Social-Network#3]
Sorry, how do I install the below npm or yarn? Thanks

1. First install all dependencies with npm or Yarn:
    ```javascript
    npm install
    ```
    or
    ```javascript
    yarn

**Comment by yTakkar** [comment]
your choice

**Comment by adesoye0** [comment]
I know. ButI have zero knowledge on its installation. Like will I create a file and past in any of the codes, or a plugin from online or what? And please, can you just give me some screen shots on how to go about it. Thanks brotherly.

**Comment by yTakkar** [comment]
First learn NodeJS & ReactJS ie. MERN stack.
Then it'll be very easy for you!!
